#!/usr/bin/env python

import requests
from bs4 import BeautifulSoup
import os
import sys

def download_image(image_url, save_path):
    try:
        response = requests.get(image_url, stream=True)
        if response.status_code == 200:
            with open(save_path, 'wb') as file:
                for chunk in response.iter_content(1024):  
                    file.write(chunk)
            print(f"Image successfully downloaded: {save_path}")
        else:
            print(f"Failed to retrieve image. Status code: {response.status_code}")
    except Exception as e:
        print(f"An error occurred: {e}")

def validate_url(url):
    split_url = url.split(".")
    if len(split_url) != 3:
        return False
    if split_url[1] != "spotify":
        return False
    return True

if __name__ == "__main__":
    url = ""
    args = sys.argv
    try:
        url = args[1]
    except:
        url = input("Please paste a spotify link to an album or track: ")

    if not validate_url(url):
        print("Input a valid spotify link!")
        exit()

    response = requests.get(url)
    html_content = response.text

    soup = BeautifulSoup(html_content, 'html.parser')

    img_tags = soup.find_all('img')
    h1_tags = soup.find_all('h1')
    title = ""
    for i in h1_tags:
        title = i.get_text()

    for img in img_tags:
        try:
            if img['loading'] == "eager":
                download_image(img['src'], title + ".png")
        except:
            print("Script either broken or outdated! (Or user error occured)")



